### ISSUE TITLE
100 Percent Data Corruption for MNAR

### ISSUE THREAD

**Issue by isabelbaer-tech** [schelterlabs/jenga#17]
Hello,

according to your documentation, users are supposed to pollute the data in fractions ranging from [0,1]. However, I am not able to set the fraction parameter =1 .0 when using the 'MNAR'-corruption. For the fraction parameter= 1.0,  I receive an Value Error. For MCAR, and MAR, it works perfectly fine. Do you know why this could be the case?

Thanks a lot!

**Comment by felixbiessmann** [comment]
Hi,

thanks for the hint, we actually always considered only use cases of fractions < 1.0 so far, so it could be considered a 'feature' and we could raise an error. 

Alternatively one could return all rows in [TabularCorruption.sample_rows](https://github.com/schelterlabs/jenga/blob/c219c645c664d2e81b7dfab2c51262e64e20f4ab/src/jenga/basis.py#L623). You would like to apply corruptions to all rows, right? 

Thanks

**Comment by isabelbaer-tech** [comment]
Hello,

Thank you for your quick reply, actually, your answer was already quite helpful. I hope you don't mind if I ask you another question with respect to the MNAR-pattern.

Yes, the idea is to pollute all data rows. I am using your framework to evaluate the impact of bad training data quality on fairness metrics. In order to do so, I am using your pollution methods to incrementally pollute the training data, train a model on each of these incrementally polluted data set, and then calculate the fairness metrics. The motivation behind these experiments is to get an understand of the impact of data quality on common fairness measures.

I chose the MNAR-pattern as it is the most systematic form of pollution; however, I think that I have not yet fully understood how exactly the MNAR pattern works. For example, let's assume that I'd like to pollute a numerical column (e.g., with values ranging from 10 to 2000) with  "gaussian noise - according to the documentation, the row x on which to corrupt the value x in column c is chosen dependent on values in column c.  How exactly does MNAR work here? How does it choose which rows to pollute and which not?


I'd be very happy if you found time to reply! Thanks a lot and have a nice day,

Isabel



________________________________
Von: felixbiessmann ***@***.***>
Gesendet: Mittwoch, 26. Oktober 2022 23:38
An: schelterlabs/jenga ***@***.***>
Cc: Isabel Baer ***@***.***>; Author ***@***.***>
Betreff: Re: [schelterlabs/jenga] 100 Percent Data Corruption for MNAR (Issue #17)


Hi,

thanks for the hint, we actually always considered only use cases of fractions < 1.0 so far, so it could be considered a 'feature' and we could raise an error.

Alternatively one could return all rows in TabularCorruption.sample_rows<https://github.com/schelterlabs/jenga/blob/c219c645c664d2e81b7dfab2c51262e64e20f4ab/src/jenga/basis.py#L623>. You would like to apply corruptions to all rows, right?

Thanks

**Comment by isabelbaer-tech** [comment]
And, as a follow-up-question: if I polluted a column with all 3 corruption patterns (MCAR with fraction=1.0, MAR= 1.0, and MNAR with fraction= 0.999999), is there any difference in the resulting polluted column? Probably not, right? If the different mechanisms determine how to choose the rows that are supposed to be polluted, and all rows are to be polluted, the results between MNAR, MAR and MCAR should be the same.
________________________________
Von: Isabel Baer ***@***.***>
Gesendet: Donnerstag, 27. Oktober 2022 13:19
An: schelterlabs/jenga ***@***.***>
Betreff: AW: [schelterlabs/jenga] 100 Percent Data Corruption for MNAR (Issue #17)

Hello,

Thank you for your quick reply, actually, your answer was already quite helpful. I hope you don't mind if I ask you another question with respect to the MNAR-pattern.

Yes, the idea is to pollute all data rows. I am using your framework to evaluate the impact of bad training data quality on fairness metrics. In order to do so, I am using your pollution methods to incrementally pollute the training data, train a model on each of these incrementally polluted data set, and then calculate the fairness metrics. The motivation behind these experiments is to get an understand of the impact of data quality on common fairness measures.

I chose the MNAR-pattern as it is the most systematic form of pollution; however, I think that I have not yet fully understood how exactly the MNAR pattern works. For example, let's assume that I'd like to pollute a numerical column (e.g., with values ranging from 10 to 2000) with  "gaussian noise - according to the documentation, the row x on which to corrupt the value x in column c is chosen dependent on values in column c.  How exactly does MNAR work here? How does it choose which rows to pollute and which not?


I'd be very happy if you found time to reply! Thanks a lot and have a nice day,

Isabel



________________________________
Von: felixbiessmann ***@***.***>
Gesendet: Mittwoch, 26. Oktober 2022 23:38
An: schelterlabs/jenga ***@***.***>
Cc: Isabel Baer ***@***.***>; Author ***@***.***>
Betreff: Re: [schelterlabs/jenga] 100 Percent Data Corruption for MNAR (Issue #17)


Hi,

thanks for the hint, we actually always considered only use cases of fractions < 1.0 so far, so it could be considered a 'feature' and we could raise an error.

Alternatively one could return all rows in TabularCorruption.sample_rows<https://github.com/schelterlabs/jenga/blob/c219c645c664d2e81b7dfab2c51262e64e20f4ab/src/jenga/basis.py#L623>. You would like to apply corruptions to all rows, right?

Thanks

**Comment by felixbiessmann** [comment]
so maybe the best way to explain the differences between the approaches is to check out [Tables 2-4 in our data imputation benchmark paper](https://www.frontiersin.org/articles/10.3389/fdata.2021.693674/full#T2). 

CAR/NAR/AR determine `which` rows/values are affected, and the different corruption types determine `how` these values will be affected. 

So to your follow up question: if all rows are affected (fraction=1.0, or close to 1.0) and as we don't sample with replacement, there is no difference in how all rows are sampled, comparing AR/NAR/CAR. 

More generally, how the NAR sampling works is probably [best explained by the code here](https://github.com/schelterlabs/jenga/blob/master/src/jenga/basis.py#L629):
* First the number of rows (i.e. the size of the percentile range) affected are computed, as well as the (random) position of that percentile, this is the same for the NAR and AR case
* For NAR, corruptions depend on the value in the corrupted column, so rows are sampled by sorting the values in the to-be-corrupted column and picking the rows corresponding to the random percentile computed before
* For AR, corruptions depend on the value in another random other column, [see also here](https://github.com/schelterlabs/jenga/blob/master/src/jenga/basis.py#L640), and the rows are sampled by sorting values in that other column and returning the corresponding rows

Hope this helps? Will also try to integrate that fraction=1.0 case

**Comment by felixbiessmann** [comment]
[this](https://github.com/schelterlabs/jenga/blob/a8bd74a588176e64183432a0124553c774adb20d/src/jenga/basis.py#L625) in the latest commit should allow for fraction=1.0 - we'll update the pip package accordingly.
